repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        name: gitleaks (pre-commit)
        entry: gitleaks protect --staged --redact --no-banner --config .gitleaks.toml
        language: golang
        stages: [pre-commit]
